name: reflective_matcher
description: Reflective matcher for Dart. Use it to simplify assert section of Unit tests
version: 0.0.1
homepage: https://github.com/syberside/reflective_matcher
author: Alexander Lozhkin <syberside@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  test: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0